# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created: Sat Nov  1 18:34:07 2008
#      by: PyQt4 UI code generator 4.4.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(563,520)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed,QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(563,520))
        Form.setMaximumSize(QtCore.QSize(563,560))
        Form.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.layoutWidget = QtGui.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(20,480,521,31))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridlayout = QtGui.QGridLayout(self.layoutWidget)
        self.gridlayout.setMargin(0)
        self.gridlayout.setSpacing(6)
        self.gridlayout.setObjectName("gridlayout")
        self.process = QtGui.QPushButton(self.layoutWidget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/button_ok.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.process.setIcon(icon)
        self.process.setObjectName("process")
        self.gridlayout.addWidget(self.process,0,1,1,1)
        self.progressBar = QtGui.QProgressBar(self.layoutWidget)
        self.progressBar.setProperty("value",QtCore.QVariant(0))
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setObjectName("progressBar")
        self.gridlayout.addWidget(self.progressBar,0,0,1,1)
        self.splitter = QtGui.QSplitter(Form)
        self.splitter.setGeometry(QtCore.QRect(0,0,16,16))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.tabWidget = QtGui.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(20,40,521,431))
        self.tabWidget.setMinimumSize(QtCore.QSize(521,431))
        self.tabWidget.setMaximumSize(QtCore.QSize(521,431))
        self.tabWidget.setObjectName("tabWidget")
        self.merge_directories = QtGui.QWidget()
        self.merge_directories.setGeometry(QtCore.QRect(0,0,517,404))
        self.merge_directories.setObjectName("merge_directories")
        self.merge_help = QtGui.QPushButton(self.merge_directories)
        self.merge_help.setGeometry(QtCore.QRect(304,370,57,27))
        self.merge_help.setMinimumSize(QtCore.QSize(57,27))
        self.merge_help.setMaximumSize(QtCore.QSize(57,27))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/help.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.merge_help.setIcon(icon)
        self.merge_help.setObjectName("merge_help")
        self.merge_delete_sources = QtGui.QPushButton(self.merge_directories)
        self.merge_delete_sources.setGeometry(QtCore.QRect(370,370,144,27))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/button_cancel.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.merge_delete_sources.setIcon(icon)
        self.merge_delete_sources.setObjectName("merge_delete_sources")
        self.merge_sources = QtGui.QTableView(self.merge_directories)
        self.merge_sources.setGeometry(QtCore.QRect(11,11,489,240))
        self.merge_sources.setObjectName("merge_sources")
        self.layoutWidget1 = QtGui.QWidget(self.merge_directories)
        self.layoutWidget1.setGeometry(QtCore.QRect(11,259,490,101))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget1)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_8 = QtGui.QLabel(self.layoutWidget1)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.label_8)
        self.merge_link = QtGui.QCheckBox(self.layoutWidget1)
        self.merge_link.setObjectName("merge_link")
        self.horizontalLayout_2.addWidget(self.merge_link)
        spacerItem = QtGui.QSpacerItem(368,20,QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout_2,0,0,1,1)
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setSpacing(6)
        self.hboxlayout.setMargin(0)
        self.hboxlayout.setObjectName("hboxlayout")
        self.label_7 = QtGui.QLabel(self.layoutWidget1)
        self.label_7.setObjectName("label_7")
        self.hboxlayout.addWidget(self.label_7)
        self.merge_destination = QtGui.QLineEdit(self.layoutWidget1)
        self.merge_destination.setObjectName("merge_destination")
        self.hboxlayout.addWidget(self.merge_destination)
        self.merge_destination_button = QtGui.QPushButton(self.layoutWidget1)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/fileopen.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.merge_destination_button.setIcon(icon)
        self.merge_destination_button.setObjectName("merge_destination_button")
        self.hboxlayout.addWidget(self.merge_destination_button)
        self.merge_delete_destination = QtGui.QPushButton(self.layoutWidget1)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/button_cancel.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.merge_delete_destination.setIcon(icon)
        self.merge_delete_destination.setObjectName("merge_delete_destination")
        self.hboxlayout.addWidget(self.merge_delete_destination)
        self.gridLayout.addLayout(self.hboxlayout,1,0,1,1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_18 = QtGui.QLabel(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred,QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(23)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        self.label_18.setMinimumSize(QtCore.QSize(0,23))
        self.label_18.setObjectName("label_18")
        self.horizontalLayout.addWidget(self.label_18)
        self.file_pattern = QtGui.QLineEdit(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.file_pattern.sizePolicy().hasHeightForWidth())
        self.file_pattern.setSizePolicy(sizePolicy)
        self.file_pattern.setObjectName("file_pattern")
        self.horizontalLayout.addWidget(self.file_pattern)
        self.gridLayout.addLayout(self.horizontalLayout,2,0,1,1)
        self.tabWidget.addTab(self.merge_directories,"")
        self.resize = QtGui.QWidget()
        self.resize.setGeometry(QtCore.QRect(0,0,517,404))
        self.resize.setObjectName("resize")
        self.layoutWidget2 = QtGui.QWidget(self.resize)
        self.layoutWidget2.setGeometry(QtCore.QRect(20,90,401,29))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.hboxlayout1 = QtGui.QHBoxLayout(self.layoutWidget2)
        self.hboxlayout1.setSpacing(6)
        self.hboxlayout1.setMargin(0)
        self.hboxlayout1.setObjectName("hboxlayout1")
        self.label_5 = QtGui.QLabel(self.layoutWidget2)
        self.label_5.setMinimumSize(QtCore.QSize(113,0))
        self.label_5.setMaximumSize(QtCore.QSize(113,16777215))
        self.label_5.setObjectName("label_5")
        self.hboxlayout1.addWidget(self.label_5)
        self.resize_newprefix = QtGui.QLineEdit(self.layoutWidget2)
        self.resize_newprefix.setObjectName("resize_newprefix")
        self.hboxlayout1.addWidget(self.resize_newprefix)
        self.layoutWidget3 = QtGui.QWidget(self.resize)
        self.layoutWidget3.setGeometry(QtCore.QRect(20,30,471,29))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.hboxlayout2 = QtGui.QHBoxLayout(self.layoutWidget3)
        self.hboxlayout2.setSpacing(6)
        self.hboxlayout2.setMargin(0)
        self.hboxlayout2.setObjectName("hboxlayout2")
        self.label = QtGui.QLabel(self.layoutWidget3)
        self.label.setObjectName("label")
        self.hboxlayout2.addWidget(self.label)
        self.resize_source = QtGui.QLineEdit(self.layoutWidget3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resize_source.sizePolicy().hasHeightForWidth())
        self.resize_source.setSizePolicy(sizePolicy)
        self.resize_source.setObjectName("resize_source")
        self.hboxlayout2.addWidget(self.resize_source)
        self.resize_source_button = QtGui.QPushButton(self.layoutWidget3)
        self.resize_source_button.setMinimumSize(QtCore.QSize(30,26))
        self.resize_source_button.setMaximumSize(QtCore.QSize(30,26))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/fileopen.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.resize_source_button.setIcon(icon)
        self.resize_source_button.setObjectName("resize_source_button")
        self.hboxlayout2.addWidget(self.resize_source_button)
        self.resize_delete_source = QtGui.QPushButton(self.layoutWidget3)
        self.resize_delete_source.setMinimumSize(QtCore.QSize(30,26))
        self.resize_delete_source.setMaximumSize(QtCore.QSize(30,26))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/button_cancel.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.resize_delete_source.setIcon(icon)
        self.resize_delete_source.setObjectName("resize_delete_source")
        self.hboxlayout2.addWidget(self.resize_delete_source)
        self.layoutWidget4 = QtGui.QWidget(self.resize)
        self.layoutWidget4.setGeometry(QtCore.QRect(20,60,401,29))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.hboxlayout3 = QtGui.QHBoxLayout(self.layoutWidget4)
        self.hboxlayout3.setSpacing(6)
        self.hboxlayout3.setMargin(0)
        self.hboxlayout3.setObjectName("hboxlayout3")
        self.label_2 = QtGui.QLabel(self.layoutWidget4)
        self.label_2.setObjectName("label_2")
        self.hboxlayout3.addWidget(self.label_2)
        self.label_3 = QtGui.QLabel(self.layoutWidget4)
        self.label_3.setMaximumSize(QtCore.QSize(20,16777215))
        self.label_3.setObjectName("label_3")
        self.hboxlayout3.addWidget(self.label_3)
        self.resize_x = QtGui.QSpinBox(self.layoutWidget4)
        self.resize_x.setMinimum(1)
        self.resize_x.setMaximum(999999999)
        self.resize_x.setProperty("value",QtCore.QVariant(800))
        self.resize_x.setObjectName("resize_x")
        self.hboxlayout3.addWidget(self.resize_x)
        self.label_4 = QtGui.QLabel(self.layoutWidget4)
        self.label_4.setMaximumSize(QtCore.QSize(20,16777215))
        self.label_4.setObjectName("label_4")
        self.hboxlayout3.addWidget(self.label_4)
        self.resize_y = QtGui.QSpinBox(self.layoutWidget4)
        self.resize_y.setMinimum(1)
        self.resize_y.setMaximum(999999999)
        self.resize_y.setProperty("value",QtCore.QVariant(800))
        self.resize_y.setObjectName("resize_y")
        self.hboxlayout3.addWidget(self.resize_y)
        self.line = QtGui.QFrame(self.resize)
        self.line.setGeometry(QtCore.QRect(10,267,501,20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.layoutWidget5 = QtGui.QWidget(self.resize)
        self.layoutWidget5.setGeometry(QtCore.QRect(10,290,481,29))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.gridlayout1 = QtGui.QGridLayout(self.layoutWidget5)
        self.gridlayout1.setMargin(0)
        self.gridlayout1.setSpacing(6)
        self.gridlayout1.setObjectName("gridlayout1")
        self.resize_destination_button = QtGui.QPushButton(self.layoutWidget5)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/fileopen.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.resize_destination_button.setIcon(icon)
        self.resize_destination_button.setObjectName("resize_destination_button")
        self.gridlayout1.addWidget(self.resize_destination_button,0,2,1,1)
        self.resize_destination = QtGui.QLineEdit(self.layoutWidget5)
        self.resize_destination.setObjectName("resize_destination")
        self.gridlayout1.addWidget(self.resize_destination,0,1,1,1)
        self.label_6 = QtGui.QLabel(self.layoutWidget5)
        self.label_6.setObjectName("label_6")
        self.gridlayout1.addWidget(self.label_6,0,0,1,1)
        self.resize_delete_destination = QtGui.QPushButton(self.layoutWidget5)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/button_cancel.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.resize_delete_destination.setIcon(icon)
        self.resize_delete_destination.setObjectName("resize_delete_destination")
        self.gridlayout1.addWidget(self.resize_delete_destination,0,3,1,1)
        self.resize_help = QtGui.QPushButton(self.resize)
        self.resize_help.setGeometry(QtCore.QRect(10,330,57,27))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/help.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.resize_help.setIcon(icon)
        self.resize_help.setObjectName("resize_help")
        self.tabWidget.addTab(self.resize,"")
        self.tab = QtGui.QWidget()
        self.tab.setGeometry(QtCore.QRect(0,0,517,404))
        self.tab.setObjectName("tab")
        self.renumerate_help = QtGui.QPushButton(self.tab)
        self.renumerate_help.setGeometry(QtCore.QRect(10,330,57,27))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/help.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.renumerate_help.setIcon(icon)
        self.renumerate_help.setObjectName("renumerate_help")
        self.line_2 = QtGui.QFrame(self.tab)
        self.line_2.setGeometry(QtCore.QRect(10,267,501,20))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.layoutWidget6 = QtGui.QWidget(self.tab)
        self.layoutWidget6.setGeometry(QtCore.QRect(20,30,471,29))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.hboxlayout4 = QtGui.QHBoxLayout(self.layoutWidget6)
        self.hboxlayout4.setSpacing(6)
        self.hboxlayout4.setMargin(0)
        self.hboxlayout4.setObjectName("hboxlayout4")
        self.label_12 = QtGui.QLabel(self.layoutWidget6)
        self.label_12.setObjectName("label_12")
        self.hboxlayout4.addWidget(self.label_12)
        self.renumerate_source = QtGui.QLineEdit(self.layoutWidget6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.renumerate_source.sizePolicy().hasHeightForWidth())
        self.renumerate_source.setSizePolicy(sizePolicy)
        self.renumerate_source.setObjectName("renumerate_source")
        self.hboxlayout4.addWidget(self.renumerate_source)
        self.renumerate_source_button = QtGui.QPushButton(self.layoutWidget6)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/fileopen.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.renumerate_source_button.setIcon(icon)
        self.renumerate_source_button.setObjectName("renumerate_source_button")
        self.hboxlayout4.addWidget(self.renumerate_source_button)
        self.renumerate_delete_source = QtGui.QPushButton(self.layoutWidget6)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/button_cancel.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.renumerate_delete_source.setIcon(icon)
        self.renumerate_delete_source.setObjectName("renumerate_delete_source")
        self.hboxlayout4.addWidget(self.renumerate_delete_source)
        self.layoutWidget7 = QtGui.QWidget(self.tab)
        self.layoutWidget7.setGeometry(QtCore.QRect(20,60,401,29))
        self.layoutWidget7.setObjectName("layoutWidget7")
        self.hboxlayout5 = QtGui.QHBoxLayout(self.layoutWidget7)
        self.hboxlayout5.setSpacing(6)
        self.hboxlayout5.setMargin(0)
        self.hboxlayout5.setObjectName("hboxlayout5")
        self.label_13 = QtGui.QLabel(self.layoutWidget7)
        self.label_13.setMinimumSize(QtCore.QSize(113,0))
        self.label_13.setMaximumSize(QtCore.QSize(113,16777215))
        self.label_13.setObjectName("label_13")
        self.hboxlayout5.addWidget(self.label_13)
        self.renumerate_basename = QtGui.QLineEdit(self.layoutWidget7)
        self.renumerate_basename.setObjectName("renumerate_basename")
        self.hboxlayout5.addWidget(self.renumerate_basename)
        self.layoutWidget8 = QtGui.QWidget(self.tab)
        self.layoutWidget8.setGeometry(QtCore.QRect(10,290,481,29))
        self.layoutWidget8.setObjectName("layoutWidget8")
        self.gridlayout2 = QtGui.QGridLayout(self.layoutWidget8)
        self.gridlayout2.setMargin(0)
        self.gridlayout2.setSpacing(6)
        self.gridlayout2.setObjectName("gridlayout2")
        self.label_14 = QtGui.QLabel(self.layoutWidget8)
        self.label_14.setObjectName("label_14")
        self.gridlayout2.addWidget(self.label_14,0,0,1,1)
        self.renumerate_select_destination_button = QtGui.QPushButton(self.layoutWidget8)
        self.renumerate_select_destination_button.setMaximumSize(QtCore.QSize(30,26))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/fileopen.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.renumerate_select_destination_button.setIcon(icon)
        self.renumerate_select_destination_button.setObjectName("renumerate_select_destination_button")
        self.gridlayout2.addWidget(self.renumerate_select_destination_button,0,3,1,1)
        self.renumerate_destination = QtGui.QLineEdit(self.layoutWidget8)
        self.renumerate_destination.setObjectName("renumerate_destination")
        self.gridlayout2.addWidget(self.renumerate_destination,0,1,1,2)
        self.renumerate_delete_destination = QtGui.QPushButton(self.layoutWidget8)
        self.renumerate_delete_destination.setMaximumSize(QtCore.QSize(30,26))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/button_cancel.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.renumerate_delete_destination.setIcon(icon)
        self.renumerate_delete_destination.setObjectName("renumerate_delete_destination")
        self.gridlayout2.addWidget(self.renumerate_delete_destination,0,4,1,1)
        self.tabWidget.addTab(self.tab,"")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setGeometry(QtCore.QRect(0,0,517,404))
        self.tab_2.setObjectName("tab_2")
        self.rotate_help = QtGui.QPushButton(self.tab_2)
        self.rotate_help.setGeometry(QtCore.QRect(10,330,57,27))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/help.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.rotate_help.setIcon(icon)
        self.rotate_help.setObjectName("rotate_help")
        self.line_3 = QtGui.QFrame(self.tab_2)
        self.line_3.setGeometry(QtCore.QRect(10,267,501,20))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.layoutWidget9 = QtGui.QWidget(self.tab_2)
        self.layoutWidget9.setGeometry(QtCore.QRect(20,60,401,29))
        self.layoutWidget9.setObjectName("layoutWidget9")
        self.hboxlayout6 = QtGui.QHBoxLayout(self.layoutWidget9)
        self.hboxlayout6.setSpacing(6)
        self.hboxlayout6.setMargin(0)
        self.hboxlayout6.setObjectName("hboxlayout6")
        self.label_17 = QtGui.QLabel(self.layoutWidget9)
        self.label_17.setMinimumSize(QtCore.QSize(113,0))
        self.label_17.setMaximumSize(QtCore.QSize(113,16777215))
        self.label_17.setObjectName("label_17")
        self.hboxlayout6.addWidget(self.label_17)
        self.rotate_newprefix = QtGui.QLineEdit(self.layoutWidget9)
        self.rotate_newprefix.setObjectName("rotate_newprefix")
        self.hboxlayout6.addWidget(self.rotate_newprefix)
        self.layoutWidget10 = QtGui.QWidget(self.tab_2)
        self.layoutWidget10.setGeometry(QtCore.QRect(20,30,471,29))
        self.layoutWidget10.setObjectName("layoutWidget10")
        self.hboxlayout7 = QtGui.QHBoxLayout(self.layoutWidget10)
        self.hboxlayout7.setSpacing(6)
        self.hboxlayout7.setMargin(0)
        self.hboxlayout7.setObjectName("hboxlayout7")
        self.label_15 = QtGui.QLabel(self.layoutWidget10)
        self.label_15.setObjectName("label_15")
        self.hboxlayout7.addWidget(self.label_15)
        self.rotate_source = QtGui.QLineEdit(self.layoutWidget10)
        self.rotate_source.setObjectName("rotate_source")
        self.hboxlayout7.addWidget(self.rotate_source)
        self.rotate_source_button = QtGui.QPushButton(self.layoutWidget10)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/fileopen.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.rotate_source_button.setIcon(icon)
        self.rotate_source_button.setObjectName("rotate_source_button")
        self.hboxlayout7.addWidget(self.rotate_source_button)
        self.rotate_delete_source = QtGui.QPushButton(self.layoutWidget10)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/button_cancel.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.rotate_delete_source.setIcon(icon)
        self.rotate_delete_source.setObjectName("rotate_delete_source")
        self.hboxlayout7.addWidget(self.rotate_delete_source)
        self.layoutWidget11 = QtGui.QWidget(self.tab_2)
        self.layoutWidget11.setGeometry(QtCore.QRect(10,290,481,29))
        self.layoutWidget11.setObjectName("layoutWidget11")
        self.gridlayout3 = QtGui.QGridLayout(self.layoutWidget11)
        self.gridlayout3.setMargin(0)
        self.gridlayout3.setSpacing(6)
        self.gridlayout3.setObjectName("gridlayout3")
        self.rotate_destination = QtGui.QLineEdit(self.layoutWidget11)
        self.rotate_destination.setObjectName("rotate_destination")
        self.gridlayout3.addWidget(self.rotate_destination,0,1,1,1)
        self.rotate_delete_destination = QtGui.QPushButton(self.layoutWidget11)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/button_cancel.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.rotate_delete_destination.setIcon(icon)
        self.rotate_delete_destination.setObjectName("rotate_delete_destination")
        self.gridlayout3.addWidget(self.rotate_delete_destination,0,3,1,1)
        self.label_16 = QtGui.QLabel(self.layoutWidget11)
        self.label_16.setObjectName("label_16")
        self.gridlayout3.addWidget(self.label_16,0,0,1,1)
        self.rotate_destination_button = QtGui.QPushButton(self.layoutWidget11)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/fileopen.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.rotate_destination_button.setIcon(icon)
        self.rotate_destination_button.setObjectName("rotate_destination_button")
        self.gridlayout3.addWidget(self.rotate_destination_button,0,2,1,1)
        self.tabWidget.addTab(self.tab_2,"")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setGeometry(QtCore.QRect(0,0,517,404))
        self.tab_3.setObjectName("tab_3")
        self.time_help = QtGui.QPushButton(self.tab_3)
        self.time_help.setGeometry(QtCore.QRect(10,330,57,27))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/help.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.time_help.setIcon(icon)
        self.time_help.setObjectName("time_help")
        self.layoutWidget12 = QtGui.QWidget(self.tab_3)
        self.layoutWidget12.setGeometry(QtCore.QRect(20,60,318,29))
        self.layoutWidget12.setObjectName("layoutWidget12")
        self.hboxlayout8 = QtGui.QHBoxLayout(self.layoutWidget12)
        self.hboxlayout8.setSpacing(6)
        self.hboxlayout8.setMargin(0)
        self.hboxlayout8.setObjectName("hboxlayout8")
        self.label_10 = QtGui.QLabel(self.layoutWidget12)
        self.label_10.setMinimumSize(QtCore.QSize(148,0))
        self.label_10.setObjectName("label_10")
        self.hboxlayout8.addWidget(self.label_10)
        self.time_real_time = QtGui.QDateTimeEdit(self.layoutWidget12)
        self.time_real_time.setObjectName("time_real_time")
        self.hboxlayout8.addWidget(self.time_real_time)
        self.layoutWidget13 = QtGui.QWidget(self.tab_3)
        self.layoutWidget13.setGeometry(QtCore.QRect(20,30,471,29))
        self.layoutWidget13.setObjectName("layoutWidget13")
        self.hboxlayout9 = QtGui.QHBoxLayout(self.layoutWidget13)
        self.hboxlayout9.setSpacing(6)
        self.hboxlayout9.setMargin(0)
        self.hboxlayout9.setObjectName("hboxlayout9")
        self.label_9 = QtGui.QLabel(self.layoutWidget13)
        self.label_9.setMinimumSize(QtCore.QSize(148,0))
        self.label_9.setObjectName("label_9")
        self.hboxlayout9.addWidget(self.label_9)
        self.time_photo_time = QtGui.QDateTimeEdit(self.layoutWidget13)
        self.time_photo_time.setObjectName("time_photo_time")
        self.hboxlayout9.addWidget(self.time_photo_time)
        self.time_select = QtGui.QPushButton(self.layoutWidget13)
        self.time_select.setMinimumSize(QtCore.QSize(0,26))
        self.time_select.setMaximumSize(QtCore.QSize(16777215,26))
        self.time_select.setObjectName("time_select")
        self.hboxlayout9.addWidget(self.time_select)
        self.layoutWidget14 = QtGui.QWidget(self.tab_3)
        self.layoutWidget14.setGeometry(QtCore.QRect(20,90,401,29))
        self.layoutWidget14.setObjectName("layoutWidget14")
        self.hboxlayout10 = QtGui.QHBoxLayout(self.layoutWidget14)
        self.hboxlayout10.setSpacing(6)
        self.hboxlayout10.setMargin(0)
        self.hboxlayout10.setObjectName("hboxlayout10")
        self.label_11 = QtGui.QLabel(self.layoutWidget14)
        self.label_11.setMinimumSize(QtCore.QSize(148,0))
        self.label_11.setObjectName("label_11")
        self.hboxlayout10.addWidget(self.label_11)
        self.time_offset = QtGui.QLineEdit(self.layoutWidget14)
        self.time_offset.setMinimumSize(QtCore.QSize(162,0))
        self.time_offset.setMaximumSize(QtCore.QSize(162,16777215))
        self.time_offset.setObjectName("time_offset")
        self.hboxlayout10.addWidget(self.time_offset)
        self.time_export = QtGui.QPushButton(self.layoutWidget14)
        self.time_export.setMinimumSize(QtCore.QSize(0,26))
        self.time_export.setMaximumSize(QtCore.QSize(16777215,26))
        self.time_export.setObjectName("time_export")
        self.hboxlayout10.addWidget(self.time_export)
        self.tabWidget.addTab(self.tab_3,"")
        self.label_8.setBuddy(self.merge_link)
        self.label_7.setBuddy(self.merge_destination)
        self.label_5.setBuddy(self.resize_newprefix)
        self.label.setBuddy(self.resize_source)
        self.label_3.setBuddy(self.resize_x)
        self.label_4.setBuddy(self.resize_y)
        self.label_12.setBuddy(self.renumerate_source)
        self.label_13.setBuddy(self.renumerate_basename)
        self.label_14.setBuddy(self.renumerate_destination)
        self.label_17.setBuddy(self.rotate_newprefix)
        self.label_15.setBuddy(self.rotate_source)
        self.label_16.setBuddy(self.rotate_destination)
        self.label_10.setBuddy(self.time_real_time)
        self.label_9.setBuddy(self.time_photo_time)
        self.label_11.setBuddy(self.time_offset)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.merge_sources,self.merge_link)
        Form.setTabOrder(self.merge_link,self.merge_destination)
        Form.setTabOrder(self.merge_destination,self.merge_delete_destination)
        Form.setTabOrder(self.merge_delete_destination,self.merge_help)
        Form.setTabOrder(self.merge_help,self.merge_delete_sources)
        Form.setTabOrder(self.merge_delete_sources,self.process)
        Form.setTabOrder(self.process,self.resize_source)
        Form.setTabOrder(self.resize_source,self.resize_delete_source)
        Form.setTabOrder(self.resize_delete_source,self.resize_x)
        Form.setTabOrder(self.resize_x,self.resize_y)
        Form.setTabOrder(self.resize_y,self.resize_newprefix)
        Form.setTabOrder(self.resize_newprefix,self.resize_destination)
        Form.setTabOrder(self.resize_destination,self.resize_destination_button)
        Form.setTabOrder(self.resize_destination_button,self.resize_help)
        Form.setTabOrder(self.resize_help,self.tabWidget)
        Form.setTabOrder(self.tabWidget,self.renumerate_source)
        Form.setTabOrder(self.renumerate_source,self.renumerate_delete_source)
        Form.setTabOrder(self.renumerate_delete_source,self.renumerate_basename)
        Form.setTabOrder(self.renumerate_basename,self.renumerate_destination)
        Form.setTabOrder(self.renumerate_destination,self.renumerate_select_destination_button)
        Form.setTabOrder(self.renumerate_select_destination_button,self.renumerate_help)
        Form.setTabOrder(self.renumerate_help,self.time_help)
        Form.setTabOrder(self.time_help,self.rotate_source)
        Form.setTabOrder(self.rotate_source,self.rotate_delete_source)
        Form.setTabOrder(self.rotate_delete_source,self.rotate_newprefix)
        Form.setTabOrder(self.rotate_newprefix,self.rotate_destination)
        Form.setTabOrder(self.rotate_destination,self.rotate_delete_destination)
        Form.setTabOrder(self.rotate_delete_destination,self.rotate_help)
        Form.setTabOrder(self.rotate_help,self.time_export)
        Form.setTabOrder(self.time_export,self.time_photo_time)
        Form.setTabOrder(self.time_photo_time,self.time_select)
        Form.setTabOrder(self.time_select,self.time_real_time)
        Form.setTabOrder(self.time_real_time,self.time_offset)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "qphotosort", None, QtGui.QApplication.UnicodeUTF8))
        self.process.setToolTip(QtGui.QApplication.translate("Form", "Starts the process", None, QtGui.QApplication.UnicodeUTF8))
        self.process.setText(QtGui.QApplication.translate("Form", "Process", None, QtGui.QApplication.UnicodeUTF8))
        self.merge_help.setText(QtGui.QApplication.translate("Form", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.merge_delete_sources.setText(QtGui.QApplication.translate("Form", "Clean all sources", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Form", "Create links: ", None, QtGui.QApplication.UnicodeUTF8))
        self.merge_link.setToolTip(QtGui.QApplication.translate("Form", "Select if you want to create links and not copies", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Form", "Destination directory: ", None, QtGui.QApplication.UnicodeUTF8))
        self.merge_destination.setToolTip(QtGui.QApplication.translate("Form", "Destination directory", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("Form", "Destination date format: ", None, QtGui.QApplication.UnicodeUTF8))
        self.file_pattern.setText(QtGui.QApplication.translate("Form", "%Y-%m-%d_%H:%M:%S-", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.merge_directories), QtGui.QApplication.translate("Form", "Merge directories", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Form", "New prefix: ", None, QtGui.QApplication.UnicodeUTF8))
        self.resize_newprefix.setToolTip(QtGui.QApplication.translate("Form", "Write if you want to add some new prefix. It can be blank", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "Source directory: ", None, QtGui.QApplication.UnicodeUTF8))
        self.resize_source.setToolTip(QtGui.QApplication.translate("Form", "Directory with source photos", None, QtGui.QApplication.UnicodeUTF8))
        self.resize_delete_source.setToolTip(QtGui.QApplication.translate("Form", "Delete files", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Form", "New size: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Form", "X: ", None, QtGui.QApplication.UnicodeUTF8))
        self.resize_x.setToolTip(QtGui.QApplication.translate("Form", "New maximum X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Form", "Y: ", None, QtGui.QApplication.UnicodeUTF8))
        self.resize_y.setToolTip(QtGui.QApplication.translate("Form", "New maximum Y", None, QtGui.QApplication.UnicodeUTF8))
        self.resize_destination.setToolTip(QtGui.QApplication.translate("Form", "Destination directory (has to exist) with resized photos", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Form", "Destination directory: ", None, QtGui.QApplication.UnicodeUTF8))
        self.resize_help.setText(QtGui.QApplication.translate("Form", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.resize), QtGui.QApplication.translate("Form", "Resize", None, QtGui.QApplication.UnicodeUTF8))
        self.renumerate_help.setText(QtGui.QApplication.translate("Form", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Form", "Source directory: ", None, QtGui.QApplication.UnicodeUTF8))
        self.renumerate_source.setToolTip(QtGui.QApplication.translate("Form", "Directory with source photos", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Form", "New basename: ", None, QtGui.QApplication.UnicodeUTF8))
        self.renumerate_basename.setToolTip(QtGui.QApplication.translate("Form", "New basename of photos", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Form", "Destination directory: ", None, QtGui.QApplication.UnicodeUTF8))
        self.renumerate_destination.setToolTip(QtGui.QApplication.translate("Form", "Destination directory. Has to exist", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("Form", "Renumerate", None, QtGui.QApplication.UnicodeUTF8))
        self.rotate_help.setText(QtGui.QApplication.translate("Form", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("Form", "New prefix: ", None, QtGui.QApplication.UnicodeUTF8))
        self.rotate_newprefix.setToolTip(QtGui.QApplication.translate("Form", "Prefix to add to photo names. It can be blank", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("Form", "Source directory: ", None, QtGui.QApplication.UnicodeUTF8))
        self.rotate_source.setToolTip(QtGui.QApplication.translate("Form", "Directory with source photos", None, QtGui.QApplication.UnicodeUTF8))
        self.rotate_destination.setToolTip(QtGui.QApplication.translate("Form", "Destination directory. Has to exist", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("Form", "Destination directory: ", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("Form", "Rotate", None, QtGui.QApplication.UnicodeUTF8))
        self.time_help.setText(QtGui.QApplication.translate("Form", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Form", "Real time: ", None, QtGui.QApplication.UnicodeUTF8))
        self.time_real_time.setToolTip(QtGui.QApplication.translate("Form", "Time that photo should be", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Form", "Photo time: ", None, QtGui.QApplication.UnicodeUTF8))
        self.time_photo_time.setToolTip(QtGui.QApplication.translate("Form", "Original time of photo", None, QtGui.QApplication.UnicodeUTF8))
        self.time_select.setToolTip(QtGui.QApplication.translate("Form", "Select a photo", None, QtGui.QApplication.UnicodeUTF8))
        self.time_select.setText(QtGui.QApplication.translate("Form", "Select a photo", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Form", "Offset (seconds): ", None, QtGui.QApplication.UnicodeUTF8))
        self.time_offset.setToolTip(QtGui.QApplication.translate("Form", "How many seconds will be added to photo", None, QtGui.QApplication.UnicodeUTF8))
        self.time_offset.setInputMask(QtGui.QApplication.translate("Form", "9999999999999999999999999999; ", None, QtGui.QApplication.UnicodeUTF8))
        self.time_export.setToolTip(QtGui.QApplication.translate("Form", "Copies offset seconds to \"Merge directory\" selected row", None, QtGui.QApplication.UnicodeUTF8))
        self.time_export.setText(QtGui.QApplication.translate("Form", "Export", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("Form", "Time calc", None, QtGui.QApplication.UnicodeUTF8))

import icons_rc
